version: '3'
services:
  apollo-router:
    container_name: apollo-router
    image: ghcr.io/apollographql/router:v1.43.0
    volumes:
      - ./supergraph-schema.graphql:/app/supergraph-schema.graphql
      - ./router.yaml:/app/router.yaml
    command: ["--dev", "-c", "/app/router.yaml", "-s", "/app/supergraph-schema.graphql", "--log", "info"]
    ports:
      - "4000:4000"